apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
  namespace: gitops-system
spec:
  destination:
    name: ''
    namespace: gitops-system
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/apps
    repoURL: 'git@github.com:fhochleitner/crossplane-demo'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - validate=false
      - CreateNamespace=true
      - ServerSideApply=true
