apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-configs
  namespace: crossplane-system
spec:
  destination:
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  source:
    path: crossplane/configurations
    repoURL: 'git@github.com:fhochleitner/crossplane-demo'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - validate=false
      - CreateNamespace=true
      - ServerSideApply=true
